//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public int SubcategoryID { get; set; }
        public int CategoryID { get; set; }
        public int Value { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
